# .github/actions/build-and-publish/action.yml
name: "Build and Publish NuGet Package"
description: "Build and publish the specified NuGet package"
inputs:
  project_name:
    description: "The name of the project"
    required: true
  dotnet_version:
    description: ".NET version to use"
    required: true
runs:
  using: "composite"
  steps:
    - uses: ./.github/actions/setup
      with:
        dotnet_version: ${{ inputs.dotnet_version }}

    - name: Build and Publish NuGet Package
      run: |
        $out = "${{ github.workspace }}\${{ inputs.project_name }}\bin\Release"

        if (Test-Path -Path $out) {
          $packagePath = Get-ChildItem -Path $out -File -Include '*.nupkg' -Recurse
        }

        if (Test-Path -Path $packagePath) {
          Write-Host Package path: $packagePath
        } else {
          Write-Host Failed to find package at $packagePath
          exit 1
        }

        $isRelease = "${{ github.ref == 'refs/heads/main' }}"

        if ($isRelease -eq 'true') {
          dotnet nuget push $packagePath --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
        }

        $version = ([xml](Get-Content -Path (Get-Item -Path $packagePath).FullName)).package.metadata.version
        echo "PACKAGE_VERSION=$version" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
      shell: pwsh

    - uses: actions/upload-artifact@v2
      with:
        name: ${{ inputs.project_name }}@${{ env.PACKAGE_VERSION }}
        path: ${{ github.workspace }}/${{ inputs.project_name }}/bin/
