// Licensed under the MIT License. See LICENSE in the project root for license information.

using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace OpenAI.Realtime
{
    public sealed class RealtimeResponseResource
    {
        /// <summary>
        /// The unique ID of the response.
        /// </summary>
        [JsonInclude]
        [JsonPropertyName("id")]
        public string Id { get; }

        /// <summary>
        /// The object type, must be "realtime.response".
        /// </summary>
        [JsonInclude]
        [JsonPropertyName("object")]
        public string Object { get; }

        /// <summary>
        /// The status of the response ("in_progress").
        /// </summary>
        [JsonInclude]
        [JsonPropertyName("status")]
        public RealtimeResponseStatus Status { get; }

        /// <summary>
        /// Additional details about the status.
        /// </summary>
        [JsonInclude]
        [JsonPropertyName("status_details")]
        public StatusDetails StatusDetails { get; }

        /// <summary>
        /// The list of output items generated by the response.
        /// </summary>
        [JsonInclude]
        [JsonPropertyName("output")]
        public IReadOnlyList<ConversationItem> Output { get; }

        /// <summary>
        /// Usage statistics for the Response, this will correspond to billing.
        /// A Realtime API session will maintain a conversation context and append new Items to the Conversation,
        /// thus output from previous turns (text and audio tokens) will become the input for later turns.
        /// </summary>
        [JsonInclude]
        [JsonPropertyName("usage")]
        public Usage Usage { get; }
    }
}
